### ISSUE TITLE
Do full environment set up

### ISSUE THREAD

**Issue by thejoefriel** [fac-14/race-to-zero#11]
- [x] Install tech stack
- [x] Write the package.json file
- [x] Create folder structure
- [x] Setup travis and codecov
