### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by SleepySheepy172** [fac-14/race-to-zero#12]
- [x] Create diagram of the schema
- [x] Write build.sql file
- [x] Write build.js
- [x] Write dbConnection.js
- [x] Make test db
- [ ] Make production db
- [x] Make dev db?
- [x] Add environment variable to travis (make sure db tests work on travis)
