### ISSUE TITLE
Set up initial testing 

### ISSUE THREAD

**Issue by Armand-Lluka** [fac-14/race-to-zero#14]
- [x] Create an initial.test.js ( with basic test)
- [x] Create a queries.test.js (for database testing) 
- [x] Create a server.test.js (for testing routes )
