### ISSUE TITLE
Sign-up/ Login

### ISSUE THREAD

**Issue by dupreesi** [fac-14/race-to-zero#2]
- [ ] Create sign up form
- [ ] Create login form
- [ ] Client side validation
- [ ] Password encryption
- [ ] Cookie management 
- [ ] Database interaction
