### ISSUE TITLE
Create challenges section

### ISSUE THREAD

**Issue by SleepySheepy172** [fac-14/race-to-zero#5]
- [x] As a logged in user I want to be able to view a list of challenges that will help me reduce waste.
- [x] As a logged in user I want to be able to click any challenge so I can find out more information about that challenge, how many points I will earn by completing it and why it matters.
- [x] As a logged in user I want to be able to accept a challenge.
- [x] As a logged in user I want to be able to view my accepted challenges.
- [x] As a logged in user I want to be able to mark my accepted challenges as completed
- [x] As a logged in user I want to be able to view my completed challenges.
- [x] As a user who has just completed a challenge I would like to see a congratulations message so that I feel good about myself.
