### ISSUE TITLE
User statistics and tracking

### ISSUE THREAD

**Issue by thejoefriel** [fac-14/race-to-zero#6]
- [x] As a logged in user I want to be able to see my rank/progress at any point.
- [x] As a logged in user who has just reached a new level I would like a congratulations message so that I don't cry myself to sleep.
- [x] As a logged in user I can select stats to get an further overview of my progress so I can see where I am.
