### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by dupreesi** [fac-14/race-to-zero#7]
- [x] As a logged in user I want to be able to view an inventory of suggested zero waste items so that I can find out what things I can buy to reduce waste.

- [x] As a logged in user I want to be able to select a suggested zero waste item so that I can learn more about why it’s good and links to recommended products.

- [x] As a logged in user I can mark zero waste items as already owned so that I can get points.
